.TH HAXEDIT 1 "February 2026"
.SH NAME
haxedit \- view and edit files in hexadecimal or in ASCII
.SH SYNOPSIS
.B haxedit
[\-s | \-\-sector] [\-m | \-\-maximize] [\-l<n> | \-\-linelength <n>] [\-\-color] [\-h | \-\-help] [filename]
.SH DESCRIPTION
.B haxedit
shows a file both in ASCII and in hexadecimal. The file can be a device as the file is read a piece at a time. You can modify the file and search through it.

.SH OPTIONS
.TP
.B \-s, \-\-sector
Use sector layout with fixed 16-byte lines.
.TP
.B \-m, \-\-maximize
Try to maximize the display.
.TP
.B \-\-color
Display colors.
.TP
.B \-l<n>, \-\-linelength <n>
Explicitly set the number of bytes to display per line to <n>.
.TP
.B \-h, \-\-help
Show the usage.

.SH COMMANDS
.SS Movement
.TP
.B Arrows, Ctrl+F/B/N/P
Move the cursor.
.TP
.B Alt+Arrows, Alt+F/B/N/P
Move by block or multiple lines.
.TP
.B Home, Ctrl+A
Go to beginning of line.
.TP
.B End, Ctrl+E
Go to end of line.
.TP
.B PageUp, Alt+V, F5
Page up.
.TP
.B PageDown, Ctrl+V, F6
Page down.
.TP
.B <, Alt+<, Esc+Home
Go to beginning of file.
.TP
.B >, Alt+>, Esc+End
Go to end of file.
.TP
.B Alt+L
Recenter view.

.SS Vim-like (Hex Pane only)
.TP
.B h, j, k, l
Move cursor (Left, Down, Up, Right).
.TP
.B w, b
Move forward/backward by block.
.TP
.B v
Set mark.
.TP
.B y
Copy region.
.TP
.B p
Paste.
.TP
.B G
Go to end of file.

.SS Miscellaneous & Editing
.TP
.B F2, Ctrl+W
Save.
.TP
.B F3, Ctrl+O
Open another file.
.TP
.B F1, Alt+H
Help.
.TP
.B Ctrl+L
Redraw.
.TP
.B Ctrl+Z
Suspend.
.TP
.B Ctrl+X, F10
Save and exit.
.TP
.B Ctrl+C
Exit without saving.
.TP
.B Tab, Ctrl+T
Toggle hex/ASCII.
.TP
.B Return, Ctrl+G, F4
Go to position (or sector).
.TP
.B Backspace
Delete backward byte.
.TP
.B Ctrl+Alt+H
Delete backward block.
.TP
.B Alt+Q, Ctrl+Q
Quoted insert.
.TP
.B Ctrl+U, Ctrl+_
Undo all modifications.
.TP
.B /, Ctrl+S
Search forward.
.TP
.B Ctrl+R
Search backward.

.SS Cut & Paste
.TP
.B Ctrl+Space, F9
Set mark.
.TP
.B Ctrl+D, Alt+W, F7
Copy selected region.
.TP
.B Ctrl+Shift+C
Copy selected region to system clipboard.
.TP
.B Ctrl+Y, Insert, F8
Paste.
.TP
.B Alt+Y, F11
Paste into a file.
.TP
.B Alt+I, F12
Fill selection with string.
.TP
.B Alt+T
Truncate file at current position.

.SH AUTHORS
Original \fBhexedit\fR by Pascal Rigaux <pixel@rigaux.org>.
\fBhaxedit\fR rewrite in Swift by euxaristia.
